import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WalletProvider } from "@/providers/Wallet";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WalletProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
          </body>
      </WalletProvider>
    </html>
  );
}
