import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import { WalletProvider } from "@/providers/Wallet";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
        <body className={inter.className}>
        <Script src="https://xumm.app/assets/cdn/xumm.min.js" strategy='beforeInteractive' />
      <Script id='xumm-setup'>
        {`
          var xumm = new Xumm('5ea5cad0-1d8e-4cee-a31e-96a8f2297dea')
      
          xumm.on("ready", () => console.log("Ready (e.g. hide loading state of page)"))
          
          xumm.on("success", async () => {
            xumm.user.account.then(account => {
              console.log(account)
            })
          })

          xumm.on("logout", async () => {
            document.getElementById('accountaddress').innerText = '...'
          })
          `}
      </Script>
      <WalletProvider>
          <Navbar />
          {children}
          </WalletProvider>
          </body>
      
    </html>
  );
}
